project_id = "lquuoriatdcspbcvgsbg"

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.bootstrap-admin]
verify_jwt = false

[functions.sync-subscriber]
verify_jwt = false
