project_id = "lquuoriatdcspbcvgsbg"

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.bootstrap-admin]
verify_jwt = false

[functions.sync-subscriber]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = true

[functions.get-available-plans]
verify_jwt = false

[functions.get-subscription-data]
verify_jwt = false

[functions.get-payment-method]
verify_jwt = true

[functions.get-payment-history]
verify_jwt = true

[functions.merge-subscribers]
verify_jwt = true

[functions.send-test-email]
verify_jwt = true

[functions.send-bulk-emails]
verify_jwt = true

[functions.send-automated-email]
verify_jwt = false
