// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lquuoriatdcspbcvgsbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxdXVvcmlhdGRjc3BiY3Znc2JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjQ2ODUsImV4cCI6MjA3MDYwMDY4NX0.N5SiWXF7IcJwksRkCRClUQyXhkmctIYJ_dQ8YCqo-IM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});